;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  Celeste Classic (remake) - for ZX Spectrum Next / N-Go
;
;  (c) 2024 David Crespo - https://github.com/dcrespo3d
;                          https://davidprograma.itch.io
;                          https://www.youtube.com/@Davidprograma
;
;  Based on Celeste Classic for Pico-8 - (c) 2015 Maddy Thorson, Noel Berry
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  This program is free software: you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation, either version 3 of the License, or
;  (at your option) any later version.  
;
;  This program is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
; 
;  You should have received a copy of the GNU General Public License
;  along with this program.  If not, see <https://www.gnu.org/licenses/>. 
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SECTION PAGE_54_MUSIC
ORG $0000

DEFW 0

PUBLIC SoundEffects

; Sound Effects for song , version 2.0, generated by Arkos Tracker 2.

SoundEffects:
SoundEffectsDisarkGenerateExternalLabel:

; The sound effects, starting at 1.
SoundEffectsDisarkPointerRegionStart0:
	defw SoundEffects_Sound1	; Sound effect 1.
	defw SoundEffects_Sound2	; Sound effect 2.
	defw SoundEffects_Sound3	; Sound effect 3.
	defw SoundEffects_Sound4	; Sound effect 4.
	defw SoundEffects_Sound5	; Sound effect 5.
	defw SoundEffects_Sound6	; Sound effect 6.
	defw SoundEffects_Sound7	; Sound effect 7.
	defw SoundEffects_Sound8	; Sound effect 8.
	defw SoundEffects_Sound9	; Sound effect 9.
	defw SoundEffects_Sound10	; Sound effect 10.
	defw SoundEffects_Sound11	; Sound effect 11.
	defw SoundEffects_Sound12	; Sound effect 12.
	defw SoundEffects_Sound13	; Sound effect 13.
	defw SoundEffects_Sound14	; Sound effect 14.
	defw SoundEffects_Sound15	; Sound effect 15.
	defw SoundEffects_Sound16	; Sound effect 16.
	defw SoundEffects_Sound17	; Sound effect 17.
	defw SoundEffects_Sound18	; Sound effect 18.
SoundEffectsDisarkPointerRegionEnd0:

SoundEffectsDisarkByteRegionStart1:
; Sound effect 1.
SoundEffects_Sound1:
	defb 0	; Speed

SoundEffects_Sound1_Loop:	defb 61	; Soft only. Volume: 15.
	defw 755	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 673	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 476	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 238	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 2.
SoundEffects_Sound2:
	defb 0	; Speed

SoundEffects_Sound2_Loop:	defb 61	; Soft only. Volume: 15.
	defw 635	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 566	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 377	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 212	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 3.
SoundEffects_Sound3:
	defb 0	; Speed

SoundEffects_Sound3_Loop:	defb 133	; Soft only. Volume: 1.
	defb 31	; Noise: 31.
	defw 7	; Software period.

	defb 137	; Soft only. Volume: 2.
	defb 26	; Noise: 26.
	defw 7	; Software period.

	defb 141	; Soft only. Volume: 3.
	defb 20	; Noise: 20.
	defw 7	; Software period.

	defb 145	; Soft only. Volume: 4.
	defb 16	; Noise: 16.
	defw 7	; Software period.

	defb 165	; Soft only. Volume: 9.
	defb 10	; Noise: 10.
	defw 2850	; Software period.

	defb 177	; Soft only. Volume: 12.
	defb 5	; Noise: 5.
	defw 1795	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 898	; Software period.

	defb 189	; Soft only. Volume: 15.
	defb 2	; Noise: 2.
	defw 951	; Software period.

	defb 185	; Soft only. Volume: 14.
	defb 4	; Noise: 4.
	defw 951	; Software period.

	defb 185	; Soft only. Volume: 14.
	defb 6	; Noise: 6.
	defw 1068	; Software period.

	defb 181	; Soft only. Volume: 13.
	defb 8	; Noise: 8.
	defw 1345	; Software period.

	defb 181	; Soft only. Volume: 13.
	defb 10	; Noise: 10.
	defw 1599	; Software period.

	defb 177	; Soft only. Volume: 12.
	defb 12	; Noise: 12.
	defw 2135	; Software period.

	defb 173	; Soft only. Volume: 11.
	defb 15	; Noise: 15.
	defw 2850	; Software period.

	defb 169	; Soft only. Volume: 10.
	defb 16	; Noise: 16.
	defw 2539	; Software period.

	defb 165	; Soft only. Volume: 9.
	defb 18	; Noise: 18.
	defw 3389	; Software period.

	defb 161	; Soft only. Volume: 8.
	defb 20	; Noise: 20.
	defw 4030	; Software period.

	defb 157	; Soft only. Volume: 7.
	defb 20	; Noise: 20.
	defw 5078	; Software period.

	defb 153	; Soft only. Volume: 6.
	defb 22	; Noise: 22.
	defw 6039	; Software period.

	defb 149	; Soft only. Volume: 5.
	defb 24	; Noise: 24.
	defw 7	; Software period.

	defb 149	; Soft only. Volume: 5.
	defb 26	; Noise: 26.
	defw 7	; Software period.

	defb 145	; Soft only. Volume: 4.
	defb 28	; Noise: 28.
	defw 7	; Software period.

	defb 145	; Soft only. Volume: 4.
	defb 31	; Noise: 31.
	defw 7	; Software period.

	defb 141	; Soft only. Volume: 3.
	defb 31	; Noise: 31.
	defw 7	; Software period.

	defb 137	; Soft only. Volume: 2.
	defb 31	; Noise: 31.
	defw 7	; Software period.

	defb 133	; Soft only. Volume: 1.
	defb 31	; Noise: 31.
	defw 7	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 4.
SoundEffects_Sound4:
	defb 0	; Speed

SoundEffects_Sound4_Loop:	defb 61	; Soft only. Volume: 15.
	defw 75	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 224	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 112	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 317	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 150	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 449	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 178	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 566	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 224	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 635	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 300	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 755	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 377	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 847	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 476	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 1068	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 599	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 1270	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 5.
SoundEffects_Sound5:
	defb 1	; Speed

SoundEffects_Sound5_Loop:	defb 61	; Soft only. Volume: 15.
	defw 712	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 300	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 599	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 238	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 449	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 189	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 356	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 133	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 252	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 100	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 178	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 79	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 141	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 59	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 106	; Software period.

	defb 33	; Soft only. Volume: 8.
	defw 47	; Software period.

	defb 33	; Soft only. Volume: 8.
	defw 79	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 6.
SoundEffects_Sound6:
	defb 0	; Speed

SoundEffects_Sound6_Loop:	defb 61	; Soft only. Volume: 15.
	defw 1008	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 1008	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 1008	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 1008	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 1068	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 1131	; Software period.

	defb 29	; Soft only. Volume: 7.
	defw 1198	; Software period.

	defb 21	; Soft only. Volume: 5.
	defw 1270	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 7.
SoundEffects_Sound7:
	defb 1	; Speed

SoundEffects_Sound7_Loop:	defb 61	; Soft only. Volume: 15.
	defw 212	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 755	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 126	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 951	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 84	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 267	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 56	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 168	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 45	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 112	; Software period.

	defb 33	; Soft only. Volume: 8.
	defw 168	; Software period.

	defb 25	; Soft only. Volume: 6.
	defw 317	; Software period.

	defb 17	; Soft only. Volume: 4.
	defw 673	; Software period.

	defb 9	; Soft only. Volume: 2.
	defw 1425	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 8.
SoundEffects_Sound8:
	defb 0	; Speed

SoundEffects_Sound8_Loop:	defb 49	; Soft only. Volume: 12.
	defw 673	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 599	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 534	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 476	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 377	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 267	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 200	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 94	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 94	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 9.
SoundEffects_Sound9:
	defb 0	; Speed

SoundEffects_Sound9_Loop:	defb 61	; Soft only. Volume: 15.
	defw 1131	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 898	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 755	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 712	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 476	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 238	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 112	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 112	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 133	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 133	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 112	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 112	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 133	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 133	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 112	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 112	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 10.
SoundEffects_Sound10:
	defb 0	; Speed

SoundEffects_Sound10_Loop:	defb 133	; Soft only. Volume: 1.
	defb 31	; Noise: 31.
	defw 4793	; Software period.

	defb 137	; Soft only. Volume: 2.
	defb 26	; Noise: 26.
	defw 4270	; Software period.

	defb 141	; Soft only. Volume: 3.
	defb 20	; Noise: 20.
	defw 4030	; Software period.

	defb 145	; Soft only. Volume: 4.
	defb 16	; Noise: 16.
	defw 3591	; Software period.

	defb 165	; Soft only. Volume: 9.
	defb 10	; Noise: 10.
	defw 951	; Software period.

	defb 177	; Soft only. Volume: 12.
	defb 5	; Noise: 5.
	defw 599	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 300	; Software period.

	defb 189	; Soft only. Volume: 15.
	defb 2	; Noise: 2.
	defw 317	; Software period.

	defb 185	; Soft only. Volume: 14.
	defb 6	; Noise: 6.
	defw 317	; Software period.

	defb 169	; Soft only. Volume: 10.
	defb 13	; Noise: 13.
	defw 356	; Software period.

	defb 149	; Soft only. Volume: 5.
	defb 22	; Noise: 22.
	defw 356	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 11.
SoundEffects_Sound11:
	defb 1	; Speed

SoundEffects_Sound11_Loop:	defb 45	; Soft only. Volume: 11.
	defw 847	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 336	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 673	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 449	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 356	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 133	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 252	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 71	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 168	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 56	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 133	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 47	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 100	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 47	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 100	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 47	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 100	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 45	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 100	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 45	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 100	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 45	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 100	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 45	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 100	; Software period.

	defb 33	; Soft only. Volume: 8.
	defw 45	; Software period.

	defb 29	; Soft only. Volume: 7.
	defw 100	; Software period.

	defb 25	; Soft only. Volume: 6.
	defw 424	; Software period.

	defb 21	; Soft only. Volume: 5.
	defw 424	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 12.
SoundEffects_Sound12:
	defb 1	; Speed

SoundEffects_Sound12_Loop:	defb 45	; Soft only. Volume: 11.
	defw 112	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 141	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 200	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 317	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 504	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 504	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 400	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 336	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 449	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 13.
SoundEffects_Sound13:
	defb 0	; Speed

SoundEffects_Sound13_Loop:	defb 57	; Soft only. Volume: 14.
	defw 1008	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 755	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 1198	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 951	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 800	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 1270	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 635	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 1131	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 847	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 1345	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 1008	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 635	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 1068	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 800	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 14.
SoundEffects_Sound14:
	defb 1	; Speed

SoundEffects_Sound14_Loop:	defb 57	; Soft only. Volume: 14.
	defw 283	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 283	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 283	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 424	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 424	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 424	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 178	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 178	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 178	; Software period.

	defb 33	; Soft only. Volume: 8.
	defw 178	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 15.
SoundEffects_Sound15:
	defb 2	; Speed

	defb 57	; Soft only. Volume: 14.
	defw 424	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 79	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 79	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 79	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 79	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 79	; Software period.

	defb 33	; Soft only. Volume: 8.
	defw 79	; Software period.

	defb 25	; Soft only. Volume: 6.
	defw 79	; Software period.

SoundEffects_Sound15_Loop:	defb 17	; Soft only. Volume: 4.
	defw 79	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 16.
SoundEffects_Sound16:
	defb 1	; Speed

SoundEffects_Sound16_Loop:	defb 53	; Soft only. Volume: 13.
	defw 141	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 238	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 159	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 141	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 238	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 159	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 141	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 238	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 159	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 17.
SoundEffects_Sound17:
	defb 4	; Speed

SoundEffects_Sound17_Loop:	defb 49	; Soft only. Volume: 12.
	defw 159	; Software period.

	defb 1	; Soft only. Volume: 0.
	defw 159	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 159	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 106	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 106	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 106	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 18.
SoundEffects_Sound18:
	defb 1	; Speed

SoundEffects_Sound18_Loop:	defb 37	; Soft only. Volume: 9.
	defw 1425	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 1198	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 1068	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 847	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 635	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 356	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 212	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 106	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 356	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 238	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 212	; Software period.

	defb 61	; Soft only. Volume: 15.
	defw 106	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 356	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 238	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 212	; Software period.

	defb 57	; Soft only. Volume: 14.
	defw 106	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 356	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 238	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 212	; Software period.

	defb 53	; Soft only. Volume: 13.
	defw 106	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 356	; Software period.

	defb 49	; Soft only. Volume: 12.
	defw 238	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 212	; Software period.

	defb 45	; Soft only. Volume: 11.
	defw 106	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 356	; Software period.

	defb 41	; Soft only. Volume: 10.
	defw 238	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 212	; Software period.

	defb 37	; Soft only. Volume: 9.
	defw 106	; Software period.

	defb 33	; Soft only. Volume: 8.
	defw 356	; Software period.

	defb 33	; Soft only. Volume: 8.
	defw 238	; Software period.

	defb 29	; Soft only. Volume: 7.
	defw 212	; Software period.

	defb 29	; Soft only. Volume: 7.
	defw 106	; Software period.

	defb 4	; End of the sound effect.

SoundEffectsDisarkByteRegionEnd1:
